# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
  #     desired widget in your `content/home/` folder.
  #   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    pageRef: /
    weight: 10
  - name: My Work
    pageRef: work/
    weight: 20
  - name: Experience
    pageRef: experience/
    weight: 30
  # - name: Tags
  #   pageRef: tags/
  #   weight: 40
  - name: Links
    pageRef: links/
    weight: 40

# footer:
#   - identifier: home
#     name: Home
#     weight: 1
#   - parent: home
#     name: Home
#     url: /
#     weight: 1
#   # - identifier: tickets
#   #   name: Tickets
#   #   weight: 2
#   # - parent: tickets
#   #   name: Get Tickets
#   #   url: https://www.eventbrite.com/
#   #   weight: 3
#   # - identifier: legal
#   #   name: Legal
#   #   weight: 3
#   # - parent: legal
#   #   name: Privacy
#   #   url: /privacy
#   #   weight: 1
#   # - parent: legal
#   #   name: Terms
#   #   url: /terms
#   #   weight: 2